language: ruby
rvm:
 - 1.9.3
 - 2.1.1
 - 2.0.0
 - 1.9.2
 - 1.8.7
 - jruby-18mode
 - jruby-19mode
 - rbx-2.1.1
 - ruby-head
 - jruby-head
 - ree
script: bundle exec jekyll build
install: bundle install
