language: ruby
rvm:
 - 2.1.1
 - 2.0.0
 - 1.9.3
 - 1.8.7
 - jruby-18mode
 - jruby-19mode
 - jruby-head
 - rbx-2.1.1
 - ree
jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk7
 - openjdk6
script: bundle exec jekyll build
install: bundle install
branches:
 only:
  - gh-pages
matrix:
 allow_failures:
  - rvm: 1.9.3
  - rvm: 1.8.7
  - rvm: jruby-18mode
  - rvm: jruby-19mode
  - rvm: jruby-head
  - rvm: rbx-2.1.1
  - rvm: ree
