sudo: false
language: ruby
rvm:
 - 2.2.x
 - 2.1.x
 - 2.0.0
 - jruby-head
 - ree
 - rbx-3.9
jdk:
 - oraclejdk8
 - oraclejdk7
 - openjdk7
 - openjdk6
script: bundle exec jekyll build
install: bundle install
branches:
 only:
  - gh-pages
matrix:
 allow_failures:
  - rvm: jruby-head
  - rvm: ree
  - rvm: rbx-3.9
